version: '3.8'

services:
  # Serviço da Aplicação (PHP)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: msb-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www # Mapeia o código local para o contêiner para desenvolvimento em tempo real
    networks:
      - laravel

  # Serviço do Servidor Web (Nginx)
  web:
    image: nginx:1.25-alpine
    container_name: msb-nginx-web
    restart: unless-stopped
    ports:
      - "8000:80" # Acessa a aplicação no navegador em http://localhost:8000
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app # Garante que o serviço do PHP suba antes do Nginx

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:15
    container_name: msb-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel-ap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@senha2
    volumes:
      - pgdata:/var/lib/postgresql/data # Persiste os dados do banco
    ports:
      - "5433:5433" # Permite conectar ao banco a partir do seu computador
    networks:
      - laravel

# Define a rede para oQs contêineres se comunicarem
networks:
  laravel:
    driver: bridge

# Define o volume para persistência dos dados do banco
volumes:
  pgdata:
    driver: local